### ISSUE TITLE
Scenario description should be synced with JIRA issue description

### ISSUE THREAD

**Issue by DmitryPrigodich** [ctco/zephyr-sync#12]
There should be possibility to sync report scenario description with JIRA issue description.
Instead of current implementation when attribute is filled via tag (@Description=) we should use json report native possibilities:
`
"name": "Scenario name",
"description": "Scenario description",
"id": "some---generated---id",
`
For CucumberReport.transform(), something like that should work:
`
test.setDescription(
    scenario.getDescription() == null ? 
        (feature.getDescription() == null ? "" :  feature.getDescription()) : 
        scenario.getDescription());
`

**Comment by IgorGursky** [comment]
Resolved in Pull Request #13
